import { TDataJustification } from "./models";

export const datatable: TDataJustification[] = [
    {
        id: 1,
        key: "1",
        no: "13123123123",
        date: "21 April 2021",
        agenda_no: "1212121",
        regarding: "test mengenai penjualan",
        justification_value: "10000000",
        creator: "doni forger",
        sub_unit: "telkom",
        last_approval: "laporan terakhir",
        code_and_budget: "ASDFA123",
        notes: "this is notes",
        document: "file.pdf",
        event_date: "30 September 2022",
        payment_estimation_date: "12 Oktober 2022",
    },
    {
        id: 2,
        key: "2",
        no: "13123123123",
        date: "21 April 2021",
        agenda_no: "1212121",
        regarding: "test laporan",
        justification_value: "10000000",
        creator: "doni salmanan",
        sub_unit: "telkom",
        last_approval: "persetujuan akhir",
        code_and_budget: "AASDF232",
        notes: "this is notes",
        document: "file.pdf",
        event_date: "30 September 2022",
        payment_estimation_date: "12 Oktober 2022",
    },
    {
        id: 3,
        key: "3",
        no: "13123123123",
        date: "21 April 2021",
        agenda_no: "1212121",
        regarding: "Penjualan",
        justification_value: "10000000",
        creator: "Nita",
        sub_unit: "telkom",
        last_approval: "Laporan akhir",
        code_and_budget: "ASDF2323",
        notes: "this is notes",
        document: "file.pdf",
        event_date: "30 September 2022",
        payment_estimation_date: "12 Oktober 2022",
    },
];

export default {};
